### ISSUE TITLE
iOS with Android Connectivity

### ISSUE THREAD

**Issue by ibrahim-sys** [CovidWorld/ios#29]
I want to ask if this iOS app is compliant with the Android App.
Do they see each other via Bluetooth?

**Comment by bielikb** [comment]
Hi @ibrahim-sys,

currently, there are couple of hiccups between the iOS <-> Android ranging, also due to the OS limitations.
In following weeks we plan to work on a version of the app that would leverage the Exposure Notification framework made by Apple & Google. we don't have ETA as our current focus is pointed towards building smart quarantine app for repatriants.

Is there anything concrete that you were interested in?

**Comment by bielikb** [comment]
Im closing this issue, @ibrahim-sys if you want to discuss some specific issue, please feel free to reach out
